[package]
name = "runtome"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "runtome-server"
path = "src/server.rs"

[[bin]]
name = "runtome"
path = "src/client.rs"

[dependencies]
actix = "0.10"
actix-codec = "0.3"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.3"
awc = "2"
p12 = "0.6.0"
env_logger = "0.8"
futures = "0.3.1"
futures-channel = "0.3.21"
bytes = "0.5.3"
lru = "0.7.2"
ringbuf = "0.2.6"
uuid = { version = "0.8", features = ["serde", "v4"] }
